#**02 - preprocesado.ipynb**
#**Integrantes**
- SANTIAGO VILLEGAS NARANJO
- JENNY ANDREA OROZCO OSORIO
- XIOMARA GIRALDO PÉREZ

#**Librerias**

In [1]:
!pip install unidecode

Collecting unidecode
  Downloading Unidecode-1.4.0-py3-none-any.whl.metadata (13 kB)
Downloading Unidecode-1.4.0-py3-none-any.whl (235 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.8/235.8 kB 5.9 MB/s eta 0:00:00
Installing collected packages: unidecode
Successfully installed unidecode-1.4.0

In [2]:
import pandas as pd
import unidecode as ud
import numpy as np
import os
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"jennyaorozcoosorio","key":"22478218cdca11a4b751e9992bf1a880"}'}

In [4]:
os.environ['KAGGLE_CONFIG_DIR'] = '.'
!chmod 600 ./kaggle.json
!kaggle competitions download -c udea-ai-4-eng-20252-pruebas-saber-pro-colombia

Downloading udea-ai-4-eng-20252-pruebas-saber-pro-colombia.zip to /content
  0% 0.00/29.9M [00:00<?, ?B/s]
100% 29.9M/29.9M [00:00<00:00, 1.05GB/s]

#**Descompresión e inspección del archivo**

In [5]:
!unzip udea*.zip > /dev/null

#**Se carga el dataset :**
- Se carga el archivo train.csv

In [6]:
data = pd.read_csv("train.csv")

In [7]:
data.columns

Index(['ID', 'PERIODO_ACADEMICO', 'E_PRGM_ACADEMICO', 'E_PRGM_DEPARTAMENTO',
       'E_VALORMATRICULAUNIVERSIDAD', 'E_HORASSEMANATRABAJA',
       'F_ESTRATOVIVIENDA', 'F_TIENEINTERNET', 'F_EDUCACIONPADRE',
       'F_TIENELAVADORA', 'F_TIENEAUTOMOVIL', 'E_PRIVADO_LIBERTAD',
       'E_PAGOMATRICULAPROPIO', 'F_TIENECOMPUTADOR', 'F_TIENEINTERNET.1',
       'F_EDUCACIONMADRE', 'RENDIMIENTO_GLOBAL', 'INDICADOR_1', 'INDICADOR_2',
       'INDICADOR_3', 'INDICADOR_4'],
      dtype='object')

#**Exploración de datos**

#**Cantidad de valores NAN por columna**

In [8]:
pd.read_csv('train.csv').isna().sum()

ID                                 0
PERIODO_ACADEMICO                  0
E_PRGM_ACADEMICO                   0
E_PRGM_DEPARTAMENTO                0
E_VALORMATRICULAUNIVERSIDAD     6287
E_HORASSEMANATRABAJA           30857
F_ESTRATOVIVIENDA              32137
F_TIENEINTERNET                26629
F_EDUCACIONPADRE               23178
F_TIENELAVADORA                39773
F_TIENEAUTOMOVIL               43623
E_PRIVADO_LIBERTAD                 0
E_PAGOMATRICULAPROPIO           6498
F_TIENECOMPUTADOR              38103
F_TIENEINTERNET.1              26629
F_EDUCACIONMADRE               23664
RENDIMIENTO_GLOBAL                 0
INDICADOR_1                        0
INDICADOR_2                        0
INDICADOR_3                        0
INDICADOR_4                        0
dtype: int64

#**Estadisticas**

In [9]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
ID,692500.0,494606.130576,285585.209455,1.0,247324.750,494564.500,741782.500,989286.000
PERIODO_ACADEMICO,692500.0,20198.366679,10.535037,20183.0,20195.000,20195.000,20203.000,20213.000
INDICADOR_1,692500.0,0.268629,0.122130,0.0,0.203,0.240,0.314,0.657
INDICADOR_2,692500.0,0.259996,0.093480,0.0,0.212,0.271,0.309,0.487
INDICADOR_3,692500.0,0.262087,0.058862,0.0,0.254,0.276,0.293,0.320
INDICADOR_4,692500.0,0.262903,0.067944,0.0,0.255,0.285,0.303,0.332

#**Valores Faltantes**

In [10]:
missing = data.isna().sum()
missing[missing > 0]

E_VALORMATRICULAUNIVERSIDAD     6287
E_HORASSEMANATRABAJA           30857
F_ESTRATOVIVIENDA              32137
F_TIENEINTERNET                26629
F_EDUCACIONPADRE               23178
F_TIENELAVADORA                39773
F_TIENEAUTOMOVIL               43623
E_PAGOMATRICULAPROPIO           6498
F_TIENECOMPUTADOR              38103
F_TIENEINTERNET.1              26629
F_EDUCACIONMADRE               23664
dtype: int64

#**Valores únicos por columna**

In [11]:
df = pd.read_csv('train.csv')
colums = df.columns

for col in df.columns:
    print(f"{col}: {df[col].nunique()}")

ID: 692500
PERIODO_ACADEMICO: 9
E_PRGM_ACADEMICO: 948
E_PRGM_DEPARTAMENTO: 31
E_VALORMATRICULAUNIVERSIDAD: 8
E_HORASSEMANATRABAJA: 5
F_ESTRATOVIVIENDA: 7
F_TIENEINTERNET: 2
F_EDUCACIONPADRE: 12
F_TIENELAVADORA: 2
F_TIENEAUTOMOVIL: 2
E_PRIVADO_LIBERTAD: 2
E_PAGOMATRICULAPROPIO: 2
F_TIENECOMPUTADOR: 2
F_TIENEINTERNET.1: 2
F_EDUCACIONMADRE: 12
RENDIMIENTO_GLOBAL: 4
INDICADOR_1: 375
INDICADOR_2: 342
INDICADOR_3: 196
INDICADOR_4: 276

#**Descripcción datos**

In [12]:
df._get_numeric_data().describe().T

,count,mean,std,min,25%,50%,75%,max
ID,692500.0,494606.130576,285585.209455,1.0,247324.750,494564.500,741782.500,989286.000
PERIODO_ACADEMICO,692500.0,20198.366679,10.535037,20183.0,20195.000,20195.000,20203.000,20213.000
INDICADOR_1,692500.0,0.268629,0.122130,0.0,0.203,0.240,0.314,0.657
INDICADOR_2,692500.0,0.259996,0.093480,0.0,0.212,0.271,0.309,0.487
INDICADOR_3,692500.0,0.262087,0.058862,0.0,0.254,0.276,0.293,0.320
INDICADOR_4,692500.0,0.262903,0.067944,0.0,0.255,0.285,0.303,0.332

#**Se guarda en la variable data**

In [13]:
data = pd.read_csv("train.csv")
print ("shape of loaded dataframe", data.shape)

shape of loaded dataframe (692500, 21)

#**one-hot para la columna 'E_PRGM_ACADEMICO'**

In [14]:
carreras_unicas = data['E_PRGM_ACADEMICO'].unique()

In [15]:
data['E_PRGM_ACADEMICO'] = data['E_PRGM_ACADEMICO'].apply(lambda x: ud.unidecode(x.lower()))

In [16]:
data.head()

,ID,PERIODO_ACADEMICO,E_PRGM_ACADEMICO,E_PRGM_DEPARTAMENTO,E_VALORMATRICULAUNIVERSIDAD,E_HORASSEMANATRABAJA,F_ESTRATOVIVIENDA,F_TIENEINTERNET,F_EDUCACIONPADRE,F_TIENELAVADORA,...,E_PRIVADO_LIBERTAD,E_PAGOMATRICULAPROPIO,F_TIENECOMPUTADOR,F_TIENEINTERNET.1,F_EDUCACIONMADRE,RENDIMIENTO_GLOBAL,INDICADOR_1,INDICADOR_2,INDICADOR_3,INDICADOR_4
0,904256,20212,enfermeria,BOGOTÁ,Entre 5.5 millones y menos de 7 millones,Menos de 10 horas,Estrato 3,Si,Técnica o tecnológica incompleta,Si,...,N,No,Si,Si,Postgrado,medio-alto,0.322,0.208,0.310,0.267
1,645256,20212,derecho,ATLANTICO,Entre 2.5 millones y menos de 4 millones,0,Estrato 3,No,Técnica o tecnológica completa,Si,...,N,No,Si,No,Técnica o tecnológica incompleta,bajo,0.311,0.215,0.292,0.264
2,308367,20203,mercadeo y publicidad,BOGOTÁ,Entre 2.5 millones y menos de 4 millones,Más de 30 horas,Estrato 3,Si,Secundaria (Bachillerato) completa,Si,...,N,No,No,Si,Secundaria (Bachillerato) completa,bajo,0.297,0.214,0.305,0.264
3,470353,20195,administracion de empresas,SANTANDER,Entre 4 millones y menos de 5.5 millones,0,Estrato 4,Si,No sabe,Si,...,N,No,Si,Si,Secundaria (Bachillerato) completa,alto,0.485,0.172,0.252,0.190
4,989032,20212,psicologia,ANTIOQUIA,Entre 2.5 millones y menos de 4 millones,Entre 21 y 30 horas,Estrato 3,Si,Primaria completa,Si,...,N,No,Si,Si,Primaria completa,medio-bajo,0.316,0.232,0.285,0.294

In [17]:
counts = data['E_PRGM_ACADEMICO'].value_counts().to_frame()
prgm_acads = (counts.loc[counts['count'] > 6000]).index
prgm_acads
len(prgm_acads)

20

In [18]:
data['E_PRGM_ACADEMICO'].value_counts()

E_PRGM_ACADEMICO
administracion de empresas                                       76679
derecho                                                          53244
contaduria publica                                               51846
psicologia                                                       49309
ingenieria industrial                                            34794
                                                                 ...
deporte y actividada fisica                                          1
licenciatura en educaci?n f?sica recreaci?n y deportes               1
licenciatura en educacion basica enfasis en ciencias sociales        1
licenciatura en educacon fisica, recreacion y deportes               1
profesional en investigacion criminal                                1
Name: count, Length: 786, dtype: int64

#**Limpieza y reemplazo de valores NAN para la columna E_HORASSEMANATRABAJA**

In [19]:
def organizar_horas_trabajadas_estudiante(data, columna):

    mapeo = {
        "0": 0,
        "menos de 10 horas": 1,
        "entre 11 y 20 horas": 2,
        "entre 21 y 30 horas": 3,
        "más de 30 horas": 4
    }

    valores_posibles = list(mapeo.keys())
    indices_nan = data[data[columna].isna()].index

    for i, idx in enumerate(indices_nan):
        data.at[idx, columna] = valores_posibles[i % len(valores_posibles)]

    data[columna] = data[columna].astype(str).str.strip().str.lower()

    data[columna] = data[columna].map(mapeo)

    return data

#**Limpieza y reemplzado de valores NAN para la columna E_HORASSEMANATRABAJA utilizando dummies**

In [20]:
def organizar_horas_trabajadas_estudiante_columna(data, columna):

    mapeo = {
        "0": 0,
        "menos de 10 horas": 1,
        "entre 11 y 20 horas": 2,
        "entre 21 y 30 horas": 3,
        "más de 30 horas": 4
    }

    valores_posibles = list(mapeo.keys())
    indices_nan = data[data[columna].isna()].index

    for i, idx in enumerate(indices_nan):
        data.at[idx, columna] = valores_posibles[i % len(valores_posibles)]

    dummies = pd.get_dummies(data[columna], prefix="Trabaja").astype(int)
    data = data.drop(columns=[columna]).join(dummies)

    return data

#**Limpieza y reemplazo de valores NAN para la columna E_PRGM_ACADEMICO**

In [21]:
def organizar_programa_estudiante(data, columna):
    categorias = {
        "salud": ["medicina", "enfermer", "fisioterap", "odontolog", "nutric", "terapia", "bacteriolog", "microbiolog", "farmac", "optometr", "salud"],
        "sociales": ["psicolog", "trabajo social", "sociolog","histor" "crimin", "politic", "juris", "derecho", "filosof","gobier","histori"],
        "administracion": ["admin", "gestión", "gestion", "logist", "mercadeo", "negocios", "marketing","direcc","gerenc"],
        "economia_finanzas": ["finanzas", "econom", "comercio", "merca"],
        "comunicacion": ["comunic", "periodismo", "medios", "publicidad","cine", "telev","fotogra","audio","publi"],
        "arte": ["arte", "musica", "teatro", "danza", "literatura", "bellas artes"],
        "educacion": ["licenc", "pedagog", "educac", "docencia","profes"],
        "diseño": ["dise","diseño","arquite"],
        "matematica": ["matema", "matemá", "estadis", "estadísti","ingenier"]
    }

    data[columna] = data[columna].astype(str).str.lower().str.strip()

    def clasificar(programa):
        for categoria, palabras_clave in categorias.items():
            if any(palabra in programa for palabra in palabras_clave):
                return categoria
        return "otras"

    data[columna] = data[columna].apply(clasificar)

    dummies = pd.get_dummies(data[columna], prefix="Programa").astype(int)
    data = data.drop(columns=[columna]).join(dummies)

    return data

#**Limpieza y reemplazado de valores NAN para la columna E_PRGM_DEPARTAMENTO**

In [22]:
def organizar_departamentos(data, columna):
  dummies = pd.get_dummies(data[columna], prefix="DEPARTAMENTO").astype(int)
  data = data.drop(columns=[columna]).join(dummies)

  return data

#**Limpieza y reemplazo de valores NAN para la columna F_ESTRATOVIVIENDA**

In [23]:
def organizar_estratos(data, columna):
  data[columna] = (
      data[columna]
      .str.lower()
      .str.replace("sin estrato", "0", regex=False)
      .str.replace("estrato ", "", regex=False))

  indices_nan = data[data[columna].isna()].index

  estratos = ["1", "2", "3", "4", "5", "6"]

  for i, idx in enumerate(indices_nan):
    data.at[idx, columna] = estratos[i % len(estratos)]

  data[columna] = (
    data[columna]
    .astype(int))

  return data

#**Limpieza y reemplazado de valores NAN para las columnas que tienen solo dos posibles valores**

In [24]:
def resumen_columna_binaria(data, columna, valores):
    si = (data[columna] == valores[0]).sum()
    no = (data[columna] == valores[1]).sum()
    nan = data[columna].isna().sum()
    total = len(data)

    si_pct = (si * 100) / total
    no_pct = (no * 100) / total
    nan_pct = (nan * 100) / total

    return (si_pct / 100), (nan_pct / 100)


def organizar_columna_binario_con_proporcion(data, columna, valores):
    n_missing = data[columna].isna().sum()

    if n_missing == 0:
        data[columna] = (data[columna]
                         .str.replace(valores[0], "1", regex=False)
                         .str.replace(valores[1], "0", regex=False)
                         .astype(int))
        print(f"No hay valores faltantes en la columna '{columna}'.")
        return data

    si_pct, nan_pct = resumen_columna_binaria(data, columna, valores)

    si = si_pct + (nan_pct / 2)
    no = 1 - si
    proporciones = [si, no]

    valores_aleatorios = np.random.choice(valores, size=n_missing, p=proporciones)
    data.loc[data[columna].isna(), columna] = valores_aleatorios

    data[columna] = (data[columna]
                     .str.replace(valores[0], "1", regex=False)
                     .str.replace(valores[1], "0", regex=False)
                     .astype(int))

    return data

#**Limpieza y reemplazo de valore NAN para la columna E_VALORMATRICULAUNIVERSIDAD utilizando dummies**

In [25]:
def organizar_valor_matricula_varias_colunas(data, columna):
  indices_nan = data[data[columna].isna()].index

  estratos = ["No pagó matrícula"]

  for i, idx in enumerate(indices_nan):
      data.at[idx, columna] = estratos[i % len(estratos)]

  dummies = pd.get_dummies(data[columna], prefix="Valor_").astype(int)
  data = data.drop(columns=[columna]).join(dummies)

  return data

#**Limpieza y reemplazo de valores NAN para la columna E_VALORMATRICULAUNIVERSIDAD**

In [26]:
def organizar_valor_matricula_en_una_columna(data, columna):
    mapeo = {
       'Entre 5.5 millones y menos de 7 millones':5,
       'Entre 2.5 millones y menos de 4 millones':3,
       'Entre 4 millones y menos de 5.5 millones':4,
       'Más de 7 millones':6,
       'Entre 1 millón y menos de 2.5 millones':2,
       'Entre 500 mil y menos de 1 millón':1,
       'Menos de 500 mil': 0,
       'No pagó matrícula':0
      }

    valores_posibles = list(mapeo.keys())
    indices_nan = data[data[columna].isna()].index

    for i, idx in enumerate(indices_nan):
        data.at[idx, columna] = valores_posibles[i % len(valores_posibles)]

    data[columna] = data[columna].astype(str).str.strip().str.lower()

    data[columna] = data[columna].map(mapeo)

    return data

#**Limpieza y reemplazo de valores NAN para la columna F_EDUCACIONPADRE**

In [27]:
def organizar_educacion_padre(data, columna):
  indices_nan = data[data[columna].isna()].index

  estratos = ['Técnica o tecnológica incompleta', 'Técnica o tecnológica completa',
  'Secundaria (Bachillerato) completa', 'No sabe', 'Primaria completa',
  'Educación profesional completa', 'Educación profesional incompleta',
  'Primaria incompleta', 'Postgrado',
  'Secundaria (Bachillerato) incompleta', 'Ninguno', 'No Aplica']

  for i, idx in enumerate(indices_nan):
      data.at[idx, columna] = estratos[i % len(estratos)]

  dummies = pd.get_dummies(data[columna], prefix="EducacionPadre").astype(int)
  data = data.drop(columns=[columna]).join(dummies)

  data=data.drop(columns=["EducacionPadre_No Aplica"])
  data=data.drop(columns=["EducacionPadre_No sabe"])
  data=data.drop(columns=["EducacionPadre_Ninguno"])
  data=data.drop(columns=["EducacionPadre_Técnica o tecnológica incompleta"])
  data=data.drop(columns=["EducacionPadre_Secundaria (Bachillerato) incompleta"])
  data=data.drop(columns=["EducacionPadre_Educación profesional incompleta"])
  data=data.drop(columns=["EducacionPadre_Primaria incompleta"])

  return data

In [28]:
dtr = pd.read_csv("train.csv")

#**Limpieza y reemplazo de valores NAN para la columna F_EDUCACIONMADRE**

In [29]:
def organizar_educacion_madre(data, columna):

  indices_nan = data[data[columna].isna()].index

  estratos = ['Postgrado', 'Técnica o tecnológica incompleta',
  'Secundaria (Bachillerato) completa', 'Primaria completa',
  'Técnica o tecnológica completa', 'Secundaria (Bachillerato) incompleta',
  'Educación profesional incompleta', 'Educación profesional completa',
  'Primaria incompleta','Ninguno', 'No Aplica', 'No sabe']

  for i, idx in enumerate(indices_nan):
      data.at[idx, columna] = estratos[i % len(estratos)]

  dummies = pd.get_dummies(data[columna], prefix="EducacionMadre").astype(int)
  data = data.drop(columns=[columna]).join(dummies)

  data=data.drop(columns=["EducacionMadre_No Aplica"])
  data=data.drop(columns=["EducacionMadre_No sabe"])
  data=data.drop(columns=["EducacionMadre_Ninguno"])
  data=data.drop(columns=["EducacionMadre_Técnica o tecnológica incompleta"])
  data=data.drop(columns=["EducacionMadre_Secundaria (Bachillerato) incompleta"])
  data=data.drop(columns=["EducacionMadre_Educación profesional incompleta"])
  data=data.drop(columns=["EducacionMadre_Primaria incompleta"])

  return data

#**Análisis de la correlación entre las columnas de indicadores**

In [30]:
indicador_cols = ['INDICADOR_1', 'INDICADOR_2', 'INDICADOR_3', 'INDICADOR_4']
dtr_indicador = dtr[indicador_cols]

indicador_matrix = dtr_indicador.corr()

print("Matriz de indicadores entre las columnas 'indicadores':")
print(indicador_matrix)

Matriz de indicadores entre las columnas 'indicadores':
             INDICADOR_1  INDICADOR_2  INDICADOR_3  INDICADOR_4
INDICADOR_1     1.000000    -0.420428     0.401190    -0.179439
INDICADOR_2    -0.420428     1.000000     0.356097     0.821443
INDICADOR_3     0.401190     0.356097     1.000000     0.726692
INDICADOR_4    -0.179439     0.821443     0.726692     1.000000

#**Función donde se eliminan columnas innecesarias y se aplican las funciones de limpieza**

In [31]:
dts = pd.read_csv("test.csv")
lentr = len(dtr)

In [32]:
def clean_data(data):
  columnas_inecesarias = ["ID", "F_TIENELAVADORA", "INDICADOR_4", "PERIODO_ACADEMICO", "F_TIENEAUTOMOVIL", "F_TIENEINTERNET.1", "E_PRIVADO_LIBERTAD"]
  data=data.drop(columns=columnas_inecesarias)

  data=organizar_horas_trabajadas_estudiante(data, "E_HORASSEMANATRABAJA")
  data=organizar_programa_estudiante(data, "E_PRGM_ACADEMICO")
  data=organizar_departamentos(data, "E_PRGM_DEPARTAMENTO")
  data=organizar_estratos(data, "F_ESTRATOVIVIENDA")
  data=organizar_columna_binario_con_proporcion(data, "F_TIENEINTERNET", ["Si", "No"])
  data=organizar_columna_binario_con_proporcion(data, "F_TIENECOMPUTADOR", ["Si", "No"])
  data=organizar_columna_binario_con_proporcion(data, "E_PAGOMATRICULAPROPIO", ["Si", "No"])

  data=organizar_valor_matricula_varias_colunas(data, "E_VALORMATRICULAUNIVERSIDAD")
  data=organizar_educacion_padre(data, "F_EDUCACIONPADRE")
  data=organizar_educacion_madre(data, "F_EDUCACIONMADRE")
  return data

In [33]:
source_cols = [i for i in dtr.columns if i!="RENDIMIENTO_GLOBAL"]
all_data = pd.concat((dtr[source_cols], dts[source_cols]))
all_data.index = range(len(all_data))
all_data = clean_data(all_data)

Xtr, ytr = all_data.iloc[:lentr].values, dtr["RENDIMIENTO_GLOBAL"].values
Xts      = all_data.iloc[lentr:].values
print (Xtr.shape, ytr.shape)
print (Xts.shape)

(692500, 67) (692500,)
(296786, 67)

In [34]:

all_data.head()

,E_HORASSEMANATRABAJA,F_ESTRATOVIVIENDA,F_TIENEINTERNET,E_PAGOMATRICULAPROPIO,F_TIENECOMPUTADOR,INDICADOR_1,INDICADOR_2,INDICADOR_3,Programa_administracion,Programa_arte,...,EducacionPadre_Educación profesional completa,EducacionPadre_Postgrado,EducacionPadre_Primaria completa,EducacionPadre_Secundaria (Bachillerato) completa,EducacionPadre_Técnica o tecnológica completa,EducacionMadre_Educación profesional completa,EducacionMadre_Postgrado,EducacionMadre_Primaria completa,EducacionMadre_Secundaria (Bachillerato) completa,EducacionMadre_Técnica o tecnológica completa
0,1,3,1,0,1,0.322,0.208,0.310,0,0,...,0,0,0,0,0,0,1,0,0,0
1,0,3,0,0,1,0.311,0.215,0.292,0,0,...,0,0,0,0,1,0,0,0,0,0
2,4,3,1,0,0,0.297,0.214,0.305,1,0,...,0,0,0,1,0,0,0,0,1,0
3,0,4,1,0,1,0.485,0.172,0.252,1,0,...,0,0,0,0,0,0,0,0,1,0
4,3,3,1,0,1,0.316,0.232,0.285,0,0,...,0,0,1,0,0,0,0,1,0,0